version: "3.5"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  bcc-node-ogmios:
    build:
      args:
        - NETWORK=${NETWORK:-mainnet}
      cache_from: [ tbco/bcc-node-ogmios:latest ]
      context: ./ogmios
    image: tbco/bcc-node-ogmios:${BCC_NODE_OGMIOS_VERSION:-v4.0.0-beta.6}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc
    
  bcc-db-sync-extended:
    image: tbco/bcc-db-sync:${BCC_DB_SYNC_VERSION:-aurum -purple-1.0.1}
    command: [
      "--config", "/config/bcc-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket",
      "--state-dir", "/data"
    ]
    environment:
      - EXTENDED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - bcc-node-ogmios
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config
      - db-sync-data:/data
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  hasura:
    build:
      context: ./packages/api-bcc-db-hasura/hasura
    image: tbco/bcc-graphql-hasura:${BCC_GRAPHQL_VERSION:-5.1.0-beta.1}
    ports:
      - ${HASURA_PORT:-8090}:8080
    depends_on:
      - "postgres"
    restart: on-failure
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:9695
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bcc-graphql:
    build:
      args:
        - NETWORK=${NETWORK:-mainnet}
        - METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://tokens.bcc.org}
      cache_from: [ tbco/bcc-graphql:latest ]
      context: .
      target: server
    image: tbco/bcc-graphql:${BCC_GRAPHQL_VERSION:-5.1.0-beta.1}-${NETWORK:-mainnet}
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
    expose:
      - ${API_PORT:-3100}
    ports:
      - ${API_PORT:-3100}:3100
    restart: on-failure
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./placeholder-secrets/postgres_db
  postgres_password:
    file: ./placeholder-secrets/postgres_password
  postgres_user:
    file: ./placeholder-secrets/postgres_user
volumes:
  db-sync-data:
  node-db:
  node-ipc:
  postgres-data:
